name: Run WeekEnd

on:
  schedule:
    - cron: "28 17 * * 5-6" # “At 17:28 on every day-of-week from Friday through Saturday.”
                            # = 19:28 'Europe/Paris' time

jobs:
  build:

    runs-on: ubuntu-latest

    # set our environment variables
    env:
      ## Environment variable
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
  
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # packages install
      - name: Installing package list
        run: apt list --installed  

      # remove prev. chrome
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  

      # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      # xvfb
      - name: Install xvfb
        run: sudo apt-get install xvfb  
      
      # requirements
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # exec script
      - name: Execute script 
        run: python3 bot/jobs/bot_weekend.py